### ISSUE TITLE
Temperature gauge isn't loading

### ISSUE THREAD

**Issue by EricChen-Tritium** [rloomans/new-teamtemp#191]
Hi, we love the team temp app https://teamtempapp.herokuapp.com/ but the temperature gauge isn't loading anymore. Is it possible to fix that?

Thanks 
![image](https://user-images.githubusercontent.com/54347405/90097092-7fe8d200-dd78-11ea-9640-e99911b15568.png)

**Comment by rloomans** [comment]
Hi Eric,

That site is deployed off a branch that I hadn't updated in a while... I've fixed it now, so it should be working for you again.

Cheers,
Rob
